set nocompatible

if has('vim_starting')
  if !exists($XDG_DATA_HOME)
    let $XDG_DATA_HOME = $HOME . '/.local/share'
  endif
  if !isdirectory($XDG_DATA_HOME . '/vim')
    call mkdir($XDG_DATA_HOME . '/vim', "p")
  endif
endif

if filereadable(expand('$HOME/.vim/vimrc_local.vim'))
  source $HOME/.vim/vimrc_local.vim
endif

set statusline=%m%f%r\ [%{&filetype}:%{&fileencoding}:%{&fileformat}]\ %l/%L\ %c\ %p%%\ %{strftime('%H:%M')}

command! ReloadVimrc execute 'source $MYVIMRC' | echo "Reloaded: " . expand('$MYVIMRC')

function! s:SetViminfo() abort
  if !exists($XDG_CACHE_HOME)
    let $XDG_CACHE_HOME = $HOME . '/.cache'
  endif
  if !isdirectory($XDG_CACHE_HOME . '/vim')
    call mkdir($XDG_CACHE_HOME . '/vim', "p")
  endif
  set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
endfunction

if has('vim_starting')
  call s:SetViminfo()
endif

" [core.filetypes]
filetype plugin indent on

" [editor.ui]
set number
set relativenumber
set showcmd
set showmatch
set list

" [editor.search]
set ignorecase
set smartcase
set hlsearch

" [editor.edit]
set expandtab
set tabstop=4
set shiftwidth=4
set hidden
set smartindent

" [editor.backup]
set nowritebackup
set nobackup
set noswapfile

" [editor.clipboard]
set clipboard+=unnamed

" [editor.ux]
set ttimeoutlen=10
set t_vb=
set novisualbell

" [editor.json]
let g:vim_json_conceal = 0

" [syntax]
syntax enable

" [leader]
let mapleader = "\<Space>"

" [mappings.normal]
nnoremap <Leader>w :w<CR>
nnoremap <Leader>p "+p<CR>
nnoremap <Leader>P "+P<CR>

" [mappings.insert]
imap <silent> jk <ESC>

" [mappings.visual]
vnoremap <silent> y y`]
vnoremap <silent> p p`]

" [autocmds.directory]
function! s:ChangeCurrentDirectory()
  let l:dir = expand("%:p:h")
  if isdirectory(fnamemodify(l:dir, ":p"))
    execute printf('lcd `=%s`', string(fnamemodify(l:dir, ":p")))
  endif
endfunction
autocmd BufEnter * call s:ChangeCurrentDirectory()

" [source.svsource]
function! s:SourceMyCompSource()
  let l:svsource = expand('~/.vim/mycompsource/svsource.vim')
  if filereadable(svsource)
    execute 'source' svsource
  endif
endfunction
call s:SourceMyCompSource()

function! s:has_plugin(name) abort
  return isdirectory(expand($XDG_DATA_HOME . '/vim/plugged/' . a:name))
endfunction

" [plugin]
call plug#begin($XDG_DATA_HOME . '/vim/plugged')
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-commentary'
Plug 'kana/vim-smartinput'
Plug 'kana/vim-textobj-user'
Plug 'kana/vim-textobj-entire'
Plug 'kana/vim-textobj-indent'
Plug 'kana/vim-textobj-line'
Plug 'bps/vim-textobj-python'
Plug 'kana/vim-operator-user'
Plug 'kana/vim-operator-replace'
Plug 'thinca/vim-quickrun'
Plug 'altercation/vim-colors-solarized'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'editorconfig/editorconfig-vim'
Plug 'hrsh7th/vim-vsnip'
Plug 'hrsh7th/vim-vsnip-integ'
Plug 'Yggdroot/indentLine'
Plug 'honza/vim-snippets'
Plug 'tpope/vim-fugitive'
Plug 'Vimjas/vim-python-pep8-indent'
Plug 'cespare/vim-toml'
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'prabirshrestha/asyncomplete-buffer.vim'
Plug 'wellle/tmux-complete.vim'
Plug 'Glench/Vim-Jinja2-Syntax'
Plug 'mattn/vim-goimports'
Plug 'junegunn/vim-easy-align'
call plug#end()

if s:has_plugin('vim-vsnip')
  let g:vsnip_snippet_dir = expand('~/.vim/mysnippets')

  imap <expr> <C-j> vsnip#expandable() ? '<Plug>(vsnip-expand)' : '<C-j>'
  smap <expr> <C-j> vsnip#expandable() ? '<Plug>(vsnip-expand)' : '<C-j>'
endif

if s:has_plugin('vim-easy-align')
  xmap ga <Plug>(EasyAlign)
  nmap ga <Plug>(EasyAlign)
endif

if s:has_plugin('vim-lsp')
  set omnifunc=lsp#complete

  " インラインの行末表示は抑制し、カーソル行の詳細だけ下部に出す
  let g:lsp_diagnostics_virtual_text_enabled = 0
  let g:lsp_diagnostics_echo_cursor = 1
  " let g:lsp_signature_help_enabled = 0

  " ruff: フォーマット時に import ソート(I)も適用し、I001 を診断にも表示
  let g:lsp_settings = {
  \ 'pylsp-all': {
  \   'workspace_config': {
  \     'pylsp': {
  \       'plugins': {
  \         'ruff': {
  \           'format': ['I'],
  \           'extendSelect': ['I'],
  \         },
  \         'pylsp_mypy': {
  \           'enabled': v:true,
  \           'live_mode': v:true,
  \         },
  \       },
  \     },
  \   },
  \ }
  \}

  nnoremap <Leader>d :<C-u>LspDefinition<CR>
  nnoremap K :<C-u>LspHover<CR>
  nnoremap <Leader>r :<C-u>LspRename<CR>
  nnoremap <Leader>n :<C-u>LspReferences<CR>
  nnoremap <Leader>f :<C-u>LspDocumentDiagnostics<CR>
  nnoremap <Leader>F :<C-u>LspDocumentFormat<CR>

  " bash-language-server: hover/diagnostics等は残し、補完候補だけ止める
  " NOTE: vim-plugのplugin/**/*.vimはvimrc読了後(VimEnter直前)にVim本体が
  " 読み込むため、vimrc内で直接 autocmd User lsp_server_init を登録すると
  " asyncomplete-lsp.vim側の登録より先に走ってしまい解除が空振りする。
  " VimEnterまで登録自体を遅らせることで、asyncomplete-lsp.vimの登録より
  " 後に発火する順序を保証する。
  function! s:DisableBashLspCompletion() abort
    call asyncomplete#unregister_source('asyncomplete_lsp_bash-language-server')
  endfunction
  function! s:SetupBashLspNoCompletion() abort
    augroup vimrc_lsp_bash_no_completion
      autocmd!
      autocmd User lsp_server_init call s:DisableBashLspCompletion()
    augroup END
  endfunction
  autocmd VimEnter * ++once call s:SetupBashLspNoCompletion()
endif

if s:has_plugin('asyncomplete-buffer.vim')
  call asyncomplete#register_source(asyncomplete#sources#buffer#get_source_options({
    \ 'name': 'buffer',
    \ 'allowlist': ['*'],
    \ 'blocklist': ['go'],
    \ 'completor': function('asyncomplete#sources#buffer#completor'),
    \ 'config': { 'max_buffer_size': 5000000 },
  \ }))
endif

if s:has_plugin('vim-quickrun')
  let g:quickrun_no_default_key_mappings = 1

  nnoremap <Leader>R :QuickRun<CR>
endif

function! s:TmuxPopupAvailable()
  let l:tmux_version = str2nr(system('tmux -V | cut -d " " -f2 | cut -c1-3 | tr -d "."'))
  return l:tmux_version >= 32
endfunction

if s:has_plugin('fzf') && s:has_plugin('fzf.vim')
  if exists('$TMUX') && s:TmuxPopupAvailable()
    let g:fzf_layout = { 'tmux': '-p80%,80%' }
  else
    let g:fzf_layout = { 'down': '40%' }
  endif

  function! s:buffer_and_cached_files()
    let l:buffers = map(filter(range(1, bufnr('$')), 'buflisted(v:val)'), 'bufname(v:val)')
    if !executable('cachef') | return l:buffers | endif
    return extend(split(system('cat $(cachef --cache-file)')), buffers)
  endfunction

  command! FZFBufferAndCachedFiles call fzf#run(fzf#wrap({
    \ 'source': reverse(s:buffer_and_cached_files()),
    \ 'sink': 'edit',
    \ 'options': '-m -x +s'
  \ }))

  nnoremap <Leader>b :FZFBufferAndCachedFiles<CR>
  nnoremap <Leader>t :Tags<CR>
  nnoremap <Leader>h :History<CR>
endif
